### ISSUE TITLE
Looks great, but cannot use

### ISSUE THREAD

**Issue by imsuperip** [toastisme/OpenBehaviourTree#3]
I think you did a really good job, so I'm going to try it out.
However, there is no editor source in the attached file and an error is occurring when trying to load the package in Unity.

**Comment by toastisme** [comment]
Ah I may have forgotten to commit something. Will have a look this evening. Thanks for pointing this out.

**Comment by toastisme** [comment]
I've just tried creating a blank Unity project (2021.2.11f1) on Windows 10. Following the installation instructions in the readme I get no errors and am able to follow the Getting Started section. Can you be more specific about the error?

**Comment by imsuperip** [comment]
#1 https://github.com/toastisme/OpenBehaviourTree.git
Using this approach (Unity 2020.3.30.f1) gives me the following error: 

[Package Manager Window] Unable to add package [https://github.com/toastisme/OpenBehaviourTree.git]:
  No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/toastisme/OpenBehaviourTree.git]:
  No 'git' executable was found. Please install Git on your system then restart Unity and Unity Hub [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

[Package Manager Window] Error adding package: https://github.com/toastisme/OpenBehaviourTree.git.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

#2 Direct Code download
![openbehaviourtree](https://user-images.githubusercontent.com/57065412/164374155-67f784e7-98e7-4dc7-be53-d1848296dca0.png)

BehaviourTree/BehaviourTreeEditor folder are empty.
All editor files are under Runtime folder.

**Comment by toastisme** [comment]
Ah I see. It looks like you don't have Git installed, which means any package installed this way would not work. Assuming you're on Windows, you can download something like [Git for Windows](https://gitforwindows.org/) (what I use). If you have got it installed it's likely an issue with your path. Some info on that [here](https://forum.unity.com/threads/no-git-executable-was-found-please-install-git-on-your-system-and-restart-unity.730511/).

**Comment by toastisme** [comment]
Closing this because I think installing Git should solve issue. But let me know if you run into any more installation issues.
