### ISSUE TITLE
Namespace "Behaviour" conflicting with Unity type Behaviour

### ISSUE THREAD

**Issue by MassfireMusic** [toastisme/OpenBehaviourTree#4]
Adding the package to project gives compilation error when not able to distinguish between namespace and type.

Suggestion: Renaming namespace to be more unique (ex. OpenBehaviourTree etc.)

**Comment by toastisme** [comment]
Sorry for the delay in replying to this (had the flu).
Thanks for pointing this out. The latest release now uses `OpenBehavourTree` instead of `Behaviour` as a namespace.

**Comment by PerFransson** [comment]
No worries and appreciate your efforts towards an open source solution for
a Unity behaviour tree.

Cheers!
Per
